apiVersion: v1
kind: Service
metadata:
  name: swathi-app
spec:
  selector:
    app: swathi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Use NodePort if running locally or ClusterIP for an internal service
